dtb-$(CONFIG_ARCH_SDM845) += sdm845-mtp.dtb

dtb-$(CONFIG_MACH_XIAOMI_E10) := xiaomi/beryllium/beryllium-mp-v2.1.dtb
dtb-$(CONFIG_MACH_XIAOMI_D5X) += xiaomi/polaris/polaris-p0.dtb \
			xiaomi/polaris/polaris-p0-v2.dtb \
			xiaomi/polaris/polaris-p1.dtb \
			xiaomi/polaris/polaris-p1-v2.dtb \
			xiaomi/polaris/polaris-p1-v2.1.dtb \
			xiaomi/polaris/polaris-p2.dtb \
			xiaomi/polaris/polaris-p2-v2.dtb \
			xiaomi/polaris/polaris-p2-v2.1.dtb \
			xiaomi/polaris/polaris-p3.dtb \
			xiaomi/polaris/polaris-p3-v2.dtb \
			xiaomi/polaris/polaris-p3-v2.1.dtb \
			xiaomi/polaris/polaris-mp.dtb \
			xiaomi/polaris/polaris-mp-v2.dtb \
			xiaomi/polaris/polaris-mp-v2.1.dtb

dtb-$(CONFIG_MACH_XIAOMI_E1N) += xiaomi/dipper/dipper-p0-v2.dtb \
                        xiaomi/dipper/dipper-p0-v2.1.dtb \
                        xiaomi/dipper/dipper-p1.1-v2.dtb \
                        xiaomi/dipper/dipper-p1.1-v2.1.dtb \
                        xiaomi/dipper/dipper-p1-v2-gb.dtb \
                        xiaomi/dipper/dipper-p1-v2-cn.dtb \
                        xiaomi/dipper/dipper-p1-v2.1-gb.dtb \
                        xiaomi/dipper/dipper-p1-v2.1-cn.dtb \
                        xiaomi/dipper/dipper-p2-v2.dtb \
                        xiaomi/dipper/dipper-p2-v2.1.dtb \
                        xiaomi/dipper/dipper-mp-v2.dtb \
                        xiaomi/dipper/dipper-mp-v2.1.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files    := *.dtb *.dtbo
